### ISSUE TITLE
Data prepareation?

### ISSUE THREAD

**Issue by panxkun** [dvl-tum/gomatch#1]
Is there any guide about the data prepareation, for example how to process megadepth for training?

**Comment by SergioRAgostinho** [comment]
Sorry for the late reply. You should follow the instruction in https://github.com/dvl-tum/gomatch/blob/main/tools/README.md. Have you tried those yet?

**Comment by panxkun** [comment]
great! I didn't see the tools for the first time. You solve my problem. Thanks

**Comment by SergioRAgostinho** [comment]
I'll move those instruction somewhere more visible.
